#!/usr/bin/env -S sh -c "echo >&2 \"Error: You are running this script instead of sourcing it. Make sure to use it as 'source setenv' or '. setenv', otherwise its settings won't take effect.\"; exit 1"

case "$-" in
*i*) ;;
*)  if [ "$1" != "-f" ]; then # allow use from scripts, as ". setenv -f"
        echo "Error: not a login shell -- run this script as 'source setenv' or '. setenv'"
        exit 1
    fi
esac

if [ ! -f bin/nasctime ]; then
    echo "Error: current working directory does not look like a nascTime root directory"
    # no exit -- it would close the shell
else
    export NASCTIME_ROOT=`pwd`
    echo "$NASCTIME_ROOT/bin added to PATH"
    export PATH="$NASCTIME_ROOT/bin:$PATH"
fi
