//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/nodes/nascTime/NwTt/GptpResidenceHeader.msg.
//

#ifndef __SIMU5G_GPTPRESIDENCEHEADER_M_H
#define __SIMU5G_GPTPRESIDENCEHEADER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class GptpResidenceHeader;

}  // namespace simu5g

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace simu5g {

/**
 * Class generated from <tt>simu5g/nodes/nascTime/NwTt/GptpResidenceHeader.msg:18</tt> by opp_msgtool.
 * <pre>
 * //
 * // Custom header carrying the NW-TT ingress timestamp through the 5GS.
 * // Models the 3GPP GTP-U PDU Session Container extension header
 * // (TS 29.281 §5.2.1) which carries residence time information.
 * //
 * class GptpResidenceHeader extends inet::FieldsChunk
 * {
 *     chunkLength = inet::B(8);
 *     simtime_t ingressTime;  // NW-TT ingress timestamp
 * }
 * </pre>
 */
class GptpResidenceHeader : public ::inet::FieldsChunk
{
  protected:
    ::omnetpp::simtime_t ingressTime = SIMTIME_ZERO;

  private:
    void copy(const GptpResidenceHeader& other);

  protected:
    bool operator==(const GptpResidenceHeader&) = delete;

  public:
    GptpResidenceHeader();
    GptpResidenceHeader(const GptpResidenceHeader& other);
    virtual ~GptpResidenceHeader();
    GptpResidenceHeader& operator=(const GptpResidenceHeader& other);
    virtual GptpResidenceHeader *dup() const override {return new GptpResidenceHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual ::omnetpp::simtime_t getIngressTime() const;
    virtual void setIngressTime(::omnetpp::simtime_t ingressTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GptpResidenceHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GptpResidenceHeader& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::GptpResidenceHeader *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::GptpResidenceHeader*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_GPTPRESIDENCEHEADER_M_H

